-- MySQL Script generated by MySQL Workbench
-- 04/16/15 17:31:26
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apibase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apibase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `apibase` ;

-- -----------------------------------------------------
-- Table `apibase`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `apibase`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`access_tokens` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  `user_agent` VARCHAR(255) NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_access_tokens_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_access_tokens_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `apibase`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`balances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`balances` (
  `id` INT UNSIGNED NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `balance` DOUBLE(12,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_balances_users1_idx` (`id` ASC),
  CONSTRAINT `fk_balances_users1`
    FOREIGN KEY (`id`)
    REFERENCES `apibase`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`offices` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`cashins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`cashins` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `office_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `ammount` DOUBLE(12,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cashins_balances1_idx` (`user_id` ASC),
  INDEX `fk_cashins_offices1_idx` (`office_id` ASC),
  CONSTRAINT `fk_cashins_balances1`
    FOREIGN KEY (`user_id`)
    REFERENCES `apibase`.`balances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cashins_offices1`
    FOREIGN KEY (`office_id`)
    REFERENCES `apibase`.`offices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`cashouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`cashouts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `office_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `ammount` DOUBLE(12,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cashouts_balances1_idx` (`user_id` ASC),
  INDEX `fk_cashouts_offices1_idx` (`office_id` ASC),
  CONSTRAINT `fk_cashouts_balances1`
    FOREIGN KEY (`user_id`)
    REFERENCES `apibase`.`balances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cashouts_offices1`
    FOREIGN KEY (`office_id`)
    REFERENCES `apibase`.`offices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`p2p_transfers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`p2p_transfers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ammout` DOUBLE(12,2) NOT NULL,
  `balance_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_p2p_transfers_balances1_idx` (`balance_id` ASC),
  INDEX `fk_p2p_transfers_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_p2p_transfers_balances1`
    FOREIGN KEY (`balance_id`)
    REFERENCES `apibase`.`balances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_p2p_transfers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `apibase`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`entities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`entities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`document_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`document_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `entity_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `alias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_types_entities1_idx` (`entity_id` ASC),
  CONSTRAINT `fk_document_types_entities1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `apibase`.`entities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`documents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `document_type_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NULL,
  `created_at` DATETIME NOT NULL,
  `published_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `summary` VARCHAR(400) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documents_document_types1_idx` (`document_type_id` ASC),
  INDEX `fk_documents_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_documents_document_types1`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `apibase`.`document_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documents_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `apibase`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`resource_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`resource_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `entity_id` INT UNSIGNED NOT NULL,
  `alias` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `allowed_mimetypes` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resource_types_entities1_idx` (`entity_id` ASC),
  CONSTRAINT `fk_resource_types_entities1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `apibase`.`entities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apibase`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apibase`.`resources` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NOT NULL,
  `mimetype` VARCHAR(100) NOT NULL,
  `filename` VARCHAR(225) NOT NULL,
  `metadata` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resources_resource_types1_idx` (`resource_type_id` ASC),
  CONSTRAINT `fk_resources_resource_types1`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `apibase`.`resource_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `apibase`.`groups`
-- -----------------------------------------------------
START TRANSACTION;
USE `apibase`;
INSERT INTO `apibase`.`groups` (`id`, `name`) VALUES (1, 'superadmin');
INSERT INTO `apibase`.`groups` (`id`, `name`) VALUES (2, 'admin');
INSERT INTO `apibase`.`groups` (`id`, `name`) VALUES (3, 'editor');
INSERT INTO `apibase`.`groups` (`id`, `name`) VALUES (4, 'customer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `apibase`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `apibase`;
INSERT INTO `apibase`.`users` (`id`, `group_id`, `created_at`, `modified_at`, `deleted_at`, `username`, `password`) VALUES (1, 1, '2015-03-31 09:00:00', '2015-03-31 09:00:00', '0000-00-00 00:00:00', 'diegoluisr@gmail.com', '$2a$08$WvRj.eL6IiogFpu3MJ.AweOXTlCs2Pygr9MaGppSLLSylUjL4b3gq');

COMMIT;

